"""
Pydantic schemas for Fashion AI application
"""

from pydantic import BaseModel, Field, validator
from typing import List, Optional, Literal
from datetime import datetime
from pathlib import Path
import mimetypes


class UploadedImage(BaseModel):
    """Represents an uploaded image file"""

    original_filename: str
    saved_path: str
    mime_type: str
    file_size: int  # bytes
    image_type: Literal["selfie", "clothing"]

    @validator('mime_type')
    def validate_mime_type(cls, v):
        """Ensure mime type is an image"""
        if not v.startswith('image/'):
            raise ValueError(f"Invalid mime type: {v}")
        return v

    @property
    def is_supported_format(self) -> bool:
        """Check if image format is supported"""
        supported = {
            'image/jpeg', 'image/jpg', 'image/png',
            'image/gif', 'image/bmp', 'image/webp',
            'image/heic', 'image/heif'  # iPhone formats
        }
        return self.mime_type.lower() in supported

    @property
    def needs_conversion(self) -> bool:
        """Check if image needs conversion for Gemini"""
        # HEIC/HEIF need conversion to JPEG
        return self.mime_type.lower() in {'image/heic', 'image/heif'}

    class Config:
        arbitrary_types_allowed = True


class ChatMessage(BaseModel):
    """Represents a single message in the chat"""

    role: Literal["user", "assistant", "system"]
    content: str
    timestamp: datetime = Field(default_factory=datetime.now)

    def to_gradient_format(self) -> dict:
        """Convert to Gradient API format"""
        return {
            "role": self.role,
            "content": self.content
        }


class ChatSession(BaseModel):
    """Represents a chat session with history"""

    session_id: str
    messages: List[ChatMessage] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.now)
    last_updated: datetime = Field(default_factory=datetime.now)

    def add_message(self, role: str, content: str) -> None:
        """Add a message to the session"""
        self.messages.append(ChatMessage(role=role, content=content))
        self.last_updated = datetime.now()

    def get_gradient_messages(self) -> List[dict]:
        """Get all messages in Gradient API format"""
        return [msg.to_gradient_format() for msg in self.messages]

    def get_context_summary(self) -> str:
        """Get a summary of the conversation context"""
        if not self.messages:
            return "No previous conversation"

        return f"{len(self.messages)} messages, started {self.created_at.strftime('%H:%M:%S')}"


class OutfitItem(BaseModel):
    """Represents a single outfit item selection"""

    index: Optional[int] = None  # Wardrobe item index
    current_item: Optional[str] = None  # e.g., "current_sneakers"
    description: str


class OutfitResponse(BaseModel):
    """Represents an outfit generated by the agent"""

    outfit_number: int
    selected_indices: List[int] = Field(default_factory=list)
    selected_paths: List[str] = Field(default_factory=list)
    reasoning: str
    wearing_instructions: str
    generated_image_path: Optional[str] = None
    error: Optional[str] = None

    class Config:
        arbitrary_types_allowed = True


class GenerationProgress(BaseModel):
    """Represents the current progress of outfit generation"""

    step: Literal[
        "starting",
        "validating_images",
        "analyzing_selfie",
        "analyzing_clothing",
        "consulting_agent",
        "generating_images",
        "complete",
        "error"
    ]
    message: str
    progress_percent: int = Field(ge=0, le=100)
    details: Optional[dict] = None

    def to_dict(self) -> dict:
        """Convert to dict for JSON serialization"""
        return {
            "step": self.step,
            "message": self.message,
            "progress_percent": self.progress_percent,
            "details": self.details or {}
        }
